spring:
  cache:
    type: redis
  redis:
    host: 139.9.2.237
    port: 6379
    jedis: # 设置Redis连接池
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
        max-active: 10
    password: ln123456